### ISSUE TITLE
Any plans for OW2 updates?

### ISSUE THREAD

**Issue by AramC92** [SnowLune/RavensAIDome#9]
Hi!

First of all, congratulations on developing this Workshop mode, it's awesome. 👍🏻

Wondering if there are there any plans on updating this to add AI code for OW2 heroes and reworked heroes from OW1?

Thanks!

**Comment by SnowLune** [comment]
So sorry for the late reply.
Yes I do plan on doing updates for this. I'm looking to find the time soon. 
The last few times I tried Overwatch 2 could not run on my PC and Workshop was unavailable.
If it's fully available again and the performance bugs with the client have been worked out I'll definitely start updating this!
